### ISSUE TITLE
[crash] NoSuchFieldError: android.net.wifi.ScanResult.timestamp

### ISSUE THREAD

**Issue by QuentinFchx** [hypery2k/cordova-hotspot-plugin#45]
Hi,

We recently had the following stacktrace using your plugin (v1.2.6):

```
Android: 4.1.1
Android Build: JRO03C
Manufacturer: HTC
Model: HTC One X
Thread: pool-1-thread-6-942
CrashReporter Key: 4C640BA3-096F-D67A-1FE8-A916DC19BFD9289B8C4A
Start Date: Sun Sep 11 06:03:45 PDT 2016
Date: Sun Sep 11 07:02:16 PDT 2016

java.lang.NoSuchFieldError: android.net.wifi.ScanResult.timestamp
    at de.martinreinhardt.cordova.plugins.hotspot.HotSpotPlugin.scanWifi(HotSpotPlugin.java:651)
    at de.martinreinhardt.cordova.plugins.hotspot.HotSpotPlugin.scanWifi(HotSpotPlugin.java:667)
    at de.martinreinhardt.cordova.plugins.hotspot.HotSpotPlugin$9.run(HotSpotPlugin.java:249)
    at de.martinreinhardt.cordova.plugins.hotspot.HotSpotPlugin$29.run(HotSpotPlugin.java:963)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:864)
```

I guess it comes from this line: https://github.com/hypery2k/cordova-hotspot-plugin/blob/master/src/android/de/martinreinhardt/cordova/plugins/hotspot/HotSpotPlugin.java#L686

It seems that the `timestamp` field was added in API.17 (https://developer.android.com/reference/android/net/wifi/ScanResult.html#timestamp)
The impacted phone might be outdated, but could we please add a small check for this specific case ?

**Comment by hypery2k** [comment]
Sorry to say, but the plugin needs  API Level 19 / Android 4.4+ to run
