### ISSUE TITLE
Process not destroyed in WifiAddresses.pingCmd

### ISSUE THREAD

**Issue by infidelkea** [hypery2k/cordova-hotspot-plugin#46]
Looks like the process is not getting destroyed after getting the result from ping command. In case you ping >256 addresses you end up getting:

```
WifiAddresses: IOException error.
java.io.IOException: Error running exec(). Command: [ping, -c, 5, -W, 1, -i, 0.2, 192.168.43.63] Working Directory: null Environment: null
   at java.lang.ProcessManager.exec(ProcessManager.java:211)
   at java.lang.Runtime.exec(Runtime.java:174)
   at java.lang.Runtime.exec(Runtime.java:247)
   at java.lang.Runtime.exec(Runtime.java:190)
   at com.mady.wifi.api.WifiAddresses.pingCmd(WifiAddresses.java:172)
   at com.myapp.managers.MyClass$PingTask.run(MyClass.java:127)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: Too many open files
   at java.lang.ProcessManager.exec(Native Method)
   at java.lang.ProcessManager.exec(ProcessManager.java:209)
```

In pingCmd: https://github.com/hypery2k/cordova-hotspot-plugin/blob/master/src/android/com/mady/wifi/api/WifiAddresses.java

adding pro.destroy() after calling pro.exitValue() solves the issue in my case.

**Comment by hypery2k** [comment]
feel free to open a PR for this

**Comment by hypery2k** [comment]
fixed in latest release
